BEGIN;

CREATE TABLE IF NOT EXISTS public.medicine_category (
    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.medicine_manufacturer (
    manufacturer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.medicine_form (
    form_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS medicine_category_name_unique_idx
    ON public.medicine_category (LOWER(BTRIM(name)));

CREATE UNIQUE INDEX IF NOT EXISTS medicine_manufacturer_name_unique_idx
    ON public.medicine_manufacturer (LOWER(BTRIM(name)));

CREATE UNIQUE INDEX IF NOT EXISTS medicine_form_name_unique_idx
    ON public.medicine_form (LOWER(BTRIM(name)));

ALTER TABLE public.medicine
    ADD COLUMN IF NOT EXISTS category_id integer,
    ADD COLUMN IF NOT EXISTS manufacturer_id integer,
    ADD COLUMN IF NOT EXISTS form_id integer;

INSERT INTO public.medicine_category (name)
SELECT DISTINCT BTRIM(category)
FROM public.medicine
WHERE category IS NOT NULL
  AND BTRIM(category) <> ''
ON CONFLICT DO NOTHING;

INSERT INTO public.medicine_manufacturer (name)
SELECT DISTINCT BTRIM(manufacturer)
FROM public.medicine
WHERE manufacturer IS NOT NULL
  AND BTRIM(manufacturer) <> ''
ON CONFLICT DO NOTHING;

INSERT INTO public.medicine_form (name)
SELECT DISTINCT BTRIM(form)
FROM public.medicine
WHERE form IS NOT NULL
  AND BTRIM(form) <> ''
ON CONFLICT DO NOTHING;

UPDATE public.medicine AS m
SET category_id = mc.category_id
FROM public.medicine_category AS mc
WHERE m.category_id IS NULL
  AND m.category IS NOT NULL
  AND BTRIM(m.category) <> ''
  AND LOWER(BTRIM(m.category)) = LOWER(BTRIM(mc.name));

UPDATE public.medicine AS m
SET manufacturer_id = mm.manufacturer_id
FROM public.medicine_manufacturer AS mm
WHERE m.manufacturer_id IS NULL
  AND m.manufacturer IS NOT NULL
  AND BTRIM(m.manufacturer) <> ''
  AND LOWER(BTRIM(m.manufacturer)) = LOWER(BTRIM(mm.name));

UPDATE public.medicine AS m
SET form_id = mf.form_id
FROM public.medicine_form AS mf
WHERE m.form_id IS NULL
  AND m.form IS NOT NULL
  AND BTRIM(m.form) <> ''
  AND LOWER(BTRIM(m.form)) = LOWER(BTRIM(mf.name));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'medicine_category_id_fkey'
    ) THEN
        ALTER TABLE public.medicine
            ADD CONSTRAINT medicine_category_id_fkey
            FOREIGN KEY (category_id) REFERENCES public.medicine_category(category_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'medicine_manufacturer_id_fkey'
    ) THEN
        ALTER TABLE public.medicine
            ADD CONSTRAINT medicine_manufacturer_id_fkey
            FOREIGN KEY (manufacturer_id) REFERENCES public.medicine_manufacturer(manufacturer_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'medicine_form_id_fkey'
    ) THEN
        ALTER TABLE public.medicine
            ADD CONSTRAINT medicine_form_id_fkey
            FOREIGN KEY (form_id) REFERENCES public.medicine_form(form_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_medicine_category_id ON public.medicine (category_id);
CREATE INDEX IF NOT EXISTS idx_medicine_manufacturer_id ON public.medicine (manufacturer_id);
CREATE INDEX IF NOT EXISTS idx_medicine_form_id ON public.medicine (form_id);

COMMIT;
