begin;

create table if not exists public.doctor_encounter_note (
  doctor_encounter_note_id bigint generated by default as identity primary key,
  visit_id integer not null unique references public.visit(visit_id) on delete cascade,
  patient_id integer not null references public.patient(patient_id) on delete cascade,
  doctor_id integer not null references public.doctor(doctor_id),
  reception_complaint text,
  doctor_note text,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

create index if not exists idx_doctor_encounter_note_patient
  on public.doctor_encounter_note(patient_id);

create index if not exists idx_doctor_encounter_note_doctor
  on public.doctor_encounter_note(doctor_id);

insert into public.doctor_encounter_note (
  visit_id,
  patient_id,
  doctor_id,
  reception_complaint,
  doctor_note
)
select
  v.visit_id,
  v.patient_id,
  v.doctor_id,
  nullif(trim(v.reason), ''),
  null
from public.visit v
where v.is_deleted = false
on conflict (visit_id) do nothing;

alter table public.prescription_medicines
  add column if not exists dosage character varying(100);

create index if not exists idx_prescription_visit_id on public.prescription(visit_id);
create index if not exists idx_lab_order_visit_id on public.lab_order(visit_id);

commit;
