alter table public.prescription_medicines
  add column if not exists available_quantity_snapshot integer,
  add column if not exists availability_status text,
  add column if not exists availability_note text;

update public.prescription_medicines
set
  available_quantity_snapshot = coalesce(available_quantity_snapshot, 0),
  availability_status = coalesce(availability_status, 'unknown')
where available_quantity_snapshot is null
   or availability_status is null;

alter table public.prescription_medicines
  alter column available_quantity_snapshot set default 0,
  alter column availability_status set default 'unknown';

create table if not exists public.prescription_fulfillment_action (
  fulfillment_action_id bigint generated by default as identity primary key,
  prescription_medicine_id integer not null references public.prescription_medicines(prescription_medicine_id) on delete cascade,
  prescription_id integer not null references public.prescription(prescription_id) on delete cascade,
  visit_id integer not null references public.visit(visit_id) on delete cascade,
  patient_id integer not null references public.patient(patient_id) on delete cascade,
  available_quantity_at_action integer not null default 0,
  action_type text not null,
  reason_code text,
  reason_note text,
  override_sale_price numeric(12,2),
  override_quantity integer,
  handled_by integer references public.staff(staff_id),
  handled_at timestamp without time zone not null default now(),
  created_at timestamp without time zone not null default now()
);

create index if not exists idx_prescription_fulfillment_action_prescription_medicine
  on public.prescription_fulfillment_action(prescription_medicine_id);

create index if not exists idx_prescription_fulfillment_action_visit
  on public.prescription_fulfillment_action(visit_id);

create table if not exists public.pharmacy_sale_override_detail (
  pharmacy_sale_override_detail_id bigint generated by default as identity primary key,
  sale_id integer not null references public.pharmacy_sale(sale_id) on delete cascade,
  prescription_medicine_id integer not null references public.prescription_medicines(prescription_medicine_id) on delete cascade,
  medicine_id integer not null references public.medicine(medicine_id),
  quantity integer not null default 0,
  unit_sale_price numeric(12,2) not null default 0,
  line_total numeric(12,2) not null default 0,
  reason_code text not null,
  reason_note text,
  handled_by integer references public.staff(staff_id),
  created_at timestamp without time zone not null default now()
);

create index if not exists idx_pharmacy_sale_override_detail_sale
  on public.pharmacy_sale_override_detail(sale_id);
